name: PHPUnit Tests

on:
  push:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: github/event-logger@v3
        with:
          php-version: 8.2.10

      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit
